# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e3a9d460f25ee78c0199b52f494cc2423ac23397505e4efd0498913ecff08e418b7f325a71b151d96d79dc10d4356cfbc407a0c741f0cd10f49d0e9f75b49e

test:
  secret_key_base: 54f93a82b929058b0ba765a824765a312d0a8a5626fd63306f2b90e01557f8636de4a917200be35979ff77abb22d0fb7f1ec4249833d0579d5f4d5081a57ef3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
